#!/bin/sh

##### Beginning of New Relic Installation #####
echo "Beginning the deployment of New Relic Java agent"

#Downloading latest agent software
echo "Downloading the latest java agent from New Relic..."
curl -o newrelic.zip http://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip

#Prepping New Relic files
echo "New Relic file download complete, unzipping archive..."
unzip newrelic.zip -d /opt/webserver && cd /opt/webserver/newrelic

#modify config file with license key
echo "Updating New Relic configuration file..."
sed -ie "s/<%= license_key %>/${NEWRELIC_LICENSE}/g" newrelic.yml
sed -ie "s/Java Application/${NEWRELIC_APPNAME}/g" newrelic.yml

# Adding JVM Argument for New Relic agent
echo "Adding JVM Argument for New Relic agent..."
cd ../bin
echo 'export CATALINA_OPTS="$CATALINA_OPTS -javaagent:/opt/webserver/newrelic/newrelic.jar"' >> setenv.sh

echo "New Relic agent install complete"